/*
 * Specification file for tiledb-server v4 API
 * This spec is exposed to the public under /v4 route group
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@tiledb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tiledb.cloud.rest_api.v4.api;

import io.tiledb.cloud.rest_api.v4.ApiException;
import io.tiledb.cloud.rest_api.v4.model.AssetGetResponse;
import io.tiledb.cloud.rest_api.v4.model.AssetListResponse;
import io.tiledb.cloud.rest_api.v4.model.AssetMetadataListResponse;
import io.tiledb.cloud.rest_api.v4.model.AssetMetadataSaveRequestInner;
import io.tiledb.cloud.rest_api.v4.model.AssetMetadataSaveResponse;
import io.tiledb.cloud.rest_api.v4.model.AssetPathResponse;
import io.tiledb.cloud.rest_api.v4.model.AssetRegisterRequest;
import io.tiledb.cloud.rest_api.v4.model.AssetType;
import io.tiledb.cloud.rest_api.v4.model.AssetUpdateRequest;
import io.tiledb.cloud.rest_api.v4.model.AssetsMoveRequest;
import io.tiledb.cloud.rest_api.v4.model.Error;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AssetsApi
 */
@Disabled
public class AssetsApiTest {

    private final AssetsApi api = new AssetsApi();

    /**
     * Delete asset metadata
     *
     * Delete one or more metadata keys for the given asset
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteAssetMetadataTest() throws ApiException {
        String workspace = null;
        String teamspace = null;
        String asset = null;
        List<String> metadataKey = null;
        Integer startTimestamp = null;
        Integer endTimestamp = null;
        api.deleteAssetMetadata(workspace, teamspace, asset, metadataKey, startTimestamp, endTimestamp);
        // TODO: test validations
    }

    /**
     * Retrieve asset
     *
     * Retrieve the asset by the given asset_id or path
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAssetTest() throws ApiException {
        String workspace = null;
        String teamspace = null;
        String asset = null;
        AssetGetResponse response = api.getAsset(workspace, teamspace, asset);
        // TODO: test validations
    }

    /**
     * Retrieve asset&#39;s metadata
     *
     * Retrieve the given asset&#39;s metadata
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAssetMetadataTest() throws ApiException {
        String workspace = null;
        String teamspace = null;
        String asset = null;
        Integer startTimestamp = null;
        Integer endTimestamp = null;
        Integer page = null;
        Integer perPage = null;
        AssetMetadataListResponse response = api.getAssetMetadata(workspace, teamspace, asset, startTimestamp, endTimestamp, page, perPage);
        // TODO: test validations
    }

    /**
     * Retrieve all assets in a given path
     *
     * Retrieve all assets in a given path, e.g., a request for &#x60;/a/b/c&#x60; will return the assets &#x60;a&#x60;, &#x60;b&#x60;, and &#x60;c&#x60;. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAssetsInPathTest() throws ApiException {
        String workspace = null;
        String teamspace = null;
        String path = null;
        AssetPathResponse response = api.getAssetsInPath(workspace, teamspace, path);
        // TODO: test validations
    }

    /**
     * Retrieves asset listing for the given teamspace
     *
     * End point to retrieve assets for the passed teamspace 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listAssetsTest() throws ApiException {
        String workspace = null;
        String teamspace = null;
        String path = null;
        Integer page = null;
        Integer perPage = null;
        AssetType assetType = null;
        String createdBy = null;
        String orderBy = null;
        String expand = null;
        Boolean includeSystemAssets = null;
        AssetListResponse response = api.listAssets(workspace, teamspace, path, page, perPage, assetType, createdBy, orderBy, expand, includeSystemAssets);
        // TODO: test validations
    }

    /**
     * Move assets (array, group &amp; files)
     *
     * Move assets (array, group &amp; files) in the specified workspace and teamspace to a target folder.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void moveAssetsTest() throws ApiException {
        String workspace = null;
        String teamspace = null;
        AssetsMoveRequest assetsMoveRequest = null;
        api.moveAssets(workspace, teamspace, assetsMoveRequest);
        // TODO: test validations
    }

    /**
     * Register an asset (array, group &amp; files)
     *
     * Register an asset for the given user in the specified workspace and teamspace.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void registerAssetTest() throws ApiException {
        String workspace = null;
        String teamspace = null;
        AssetRegisterRequest assetRegisterRequest = null;
        api.registerAsset(workspace, teamspace, assetRegisterRequest);
        // TODO: test validations
    }

    /**
     * Update asset
     *
     * Update the asset by the given asset_id or path
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateAssetTest() throws ApiException {
        String workspace = null;
        String teamspace = null;
        String asset = null;
        AssetUpdateRequest assetUpdateRequest = null;
        api.updateAsset(workspace, teamspace, asset, assetUpdateRequest);
        // TODO: test validations
    }

    /**
     * Update the given asset&#39;s metadata pair
     *
     * Update asset&#39;s metadata
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateAssetMetadataTest() throws ApiException {
        String workspace = null;
        String teamspace = null;
        String asset = null;
        List<AssetMetadataSaveRequestInner> assetMetadataSaveRequestInner = null;
        Integer startTimestamp = null;
        Integer endTimestamp = null;
        AssetMetadataSaveResponse response = api.updateAssetMetadata(workspace, teamspace, asset, assetMetadataSaveRequestInner, startTimestamp, endTimestamp);
        // TODO: test validations
    }

}
