/*
 * Specification file for tiledb-server v4 API
 * This spec is exposed to the public under /v4 route group
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@tiledb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tiledb.cloud.rest_api.v4.api;

import io.tiledb.cloud.rest_api.v4.ApiException;
import io.tiledb.cloud.rest_api.v4.model.ErrorResponse;
import io.tiledb.cloud.rest_api.v4.model.ListShareSchemaTablesResponse;
import io.tiledb.cloud.rest_api.v4.model.ListShareSchemasResponse;
import io.tiledb.cloud.rest_api.v4.model.ListSharesResponse;
import io.tiledb.cloud.rest_api.v4.model.ListTablesResponse;
import io.tiledb.cloud.rest_api.v4.model.QueryTableChangeResponse;
import io.tiledb.cloud.rest_api.v4.model.QueryTableRequest;
import io.tiledb.cloud.rest_api.v4.model.QueryTableResponse;
import io.tiledb.cloud.rest_api.v4.model.ShareResponse;
import io.tiledb.cloud.rest_api.v4.model.TableMetadataResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DeltasharingApi
 */
@Disabled
public class DeltasharingApiTest {

    private final DeltasharingApi api = new DeltasharingApi();

    /**
     * get a delta share
     *
     * This is the API to get the metadata of a share.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getShareTest() throws ApiException {
        String workspace = null;
        ShareResponse response = api.getShare(workspace);
        // TODO: test validations
    }

    /**
     * list delta share schema tables
     *
     * This is the API to list tables in a schema.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listShareAllTablesTest() throws ApiException {
        String workspace = null;
        Integer maxResults = null;
        String pageToken = null;
        ListTablesResponse response = api.listShareAllTables(workspace, maxResults, pageToken);
        // TODO: test validations
    }

    /**
     * list delta share schema tables
     *
     * This is the API to list tables in a schema.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listShareSchemaTablesTest() throws ApiException {
        String workspace = null;
        String teamspace = null;
        Integer maxResults = null;
        String pageToken = null;
        ListShareSchemaTablesResponse response = api.listShareSchemaTables(workspace, teamspace, maxResults, pageToken);
        // TODO: test validations
    }

    /**
     * list delta share schemas
     *
     * This is the API to list schemas in a share.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listShareSchemasTest() throws ApiException {
        String workspace = null;
        Integer maxResults = null;
        String pageToken = null;
        ListShareSchemasResponse response = api.listShareSchemas(workspace, maxResults, pageToken);
        // TODO: test validations
    }

    /**
     * list delta shares
     *
     * This is the API to list shares accessible to a recipient.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listSharesTest() throws ApiException {
        Integer maxResults = null;
        String pageToken = null;
        ListSharesResponse response = api.listShares(maxResults, pageToken);
        // TODO: test validations
    }

    /**
     * query table
     *
     * This is the API for clients to read data from a table.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryTableTest() throws ApiException {
        String workspace = null;
        String teamspace = null;
        String asset = null;
        QueryTableRequest queryTableRequest = null;
        QueryTableResponse response = api.queryTable(workspace, teamspace, asset, queryTableRequest);
        // TODO: test validations
    }

    /**
     * query table changes
     *
     * This is the API for clients to read change data feed from a table.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryTableChangesTest() throws ApiException {
        String workspace = null;
        String teamspace = null;
        String asset = null;
        Long startingVersion = null;
        String startingTimestamp = null;
        Long endingVersion = null;
        String endingTimestamp = null;
        Boolean includeHistoricalMetadata = null;
        QueryTableChangeResponse response = api.queryTableChanges(workspace, teamspace, asset, startingVersion, startingTimestamp, endingVersion, endingTimestamp, includeHistoricalMetadata);
        // TODO: test validations
    }

    /**
     * fetch table metadata
     *
     * This is the API for clients to query the table schema and other metadata.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryTableMetadataTest() throws ApiException {
        String workspace = null;
        String teamspace = null;
        String asset = null;
        TableMetadataResponse response = api.queryTableMetadata(workspace, teamspace, asset);
        // TODO: test validations
    }

    /**
     * fetch table version
     *
     * This is the API for clients to get a table version without any other extra information
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryTableVerisonTest() throws ApiException {
        String workspace = null;
        String teamspace = null;
        String asset = null;
        String startingTimestamp = null;
        api.queryTableVerison(workspace, teamspace, asset, startingTimestamp);
        // TODO: test validations
    }

}
