/*
 * Specification file for tiledb-server v4 API
 * This spec is exposed to the public under /v4 route group
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@tiledb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tiledb.cloud.rest_api.v4.api;

import io.tiledb.cloud.rest_api.v4.ApiException;
import io.tiledb.cloud.rest_api.v4.model.Error;
import io.tiledb.cloud.rest_api.v4.model.VersionsResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VersionsApi
 */
@Disabled
public class VersionsApiTest {

    private final VersionsApi api = new VersionsApi();

    /**
     * Get Server versions
     *
     * This endpoint returns various version numbers pertaining to the server. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getVersionsTest() throws ApiException {
        VersionsResponse response = api.getVersions();
        // TODO: test validations
    }

}
