/*
 * Tiledb Storage Platform API
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tiledb.cloud.rest_api.v2.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.tiledb.cloud.rest_api.v2.model.FragmentIndex;
import io.tiledb.cloud.rest_api.v2.model.ResultCellSlab;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.tiledb.cloud.rest_api.v2.JSON;

/**
 * State of reader
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-30T04:47:07.570140+03:00[Europe/Athens]", comments = "Generator version: 7.7.0")
public class ReadStateIndex {
  public static final String SERIALIZED_NAME_DONE_ADDING_RESULT_TILES = "doneAddingResultTiles";
  @SerializedName(SERIALIZED_NAME_DONE_ADDING_RESULT_TILES)
  private Boolean doneAddingResultTiles;

  public static final String SERIALIZED_NAME_FRAG_TILE_IDX = "fragTileIdx";
  @SerializedName(SERIALIZED_NAME_FRAG_TILE_IDX)
  private List<FragmentIndex> fragTileIdx = new ArrayList<>();

  public static final String SERIALIZED_NAME_RESULT_CELL_SLAB = "resultCellSlab";
  @SerializedName(SERIALIZED_NAME_RESULT_CELL_SLAB)
  private List<ResultCellSlab> resultCellSlab = new ArrayList<>();

  public ReadStateIndex() {
  }

  public ReadStateIndex doneAddingResultTiles(Boolean doneAddingResultTiles) {
    this.doneAddingResultTiles = doneAddingResultTiles;
    return this;
  }

  /**
   * Is the reader done adding result tiles.
   * @return doneAddingResultTiles
   */
  @javax.annotation.Nullable
  public Boolean getDoneAddingResultTiles() {
    return doneAddingResultTiles;
  }

  public void setDoneAddingResultTiles(Boolean doneAddingResultTiles) {
    this.doneAddingResultTiles = doneAddingResultTiles;
  }


  public ReadStateIndex fragTileIdx(List<FragmentIndex> fragTileIdx) {
    this.fragTileIdx = fragTileIdx;
    return this;
  }

  public ReadStateIndex addFragTileIdxItem(FragmentIndex fragTileIdxItem) {
    if (this.fragTileIdx == null) {
      this.fragTileIdx = new ArrayList<>();
    }
    this.fragTileIdx.add(fragTileIdxItem);
    return this;
  }

  /**
   * Tile/cell index for each fragments.
   * @return fragTileIdx
   */
  @javax.annotation.Nullable
  public List<FragmentIndex> getFragTileIdx() {
    return fragTileIdx;
  }

  public void setFragTileIdx(List<FragmentIndex> fragTileIdx) {
    this.fragTileIdx = fragTileIdx;
  }


  public ReadStateIndex resultCellSlab(List<ResultCellSlab> resultCellSlab) {
    this.resultCellSlab = resultCellSlab;
    return this;
  }

  public ReadStateIndex addResultCellSlabItem(ResultCellSlab resultCellSlabItem) {
    if (this.resultCellSlab == null) {
      this.resultCellSlab = new ArrayList<>();
    }
    this.resultCellSlab.add(resultCellSlabItem);
    return this;
  }

  /**
   * Result cell slab.
   * @return resultCellSlab
   */
  @javax.annotation.Nullable
  public List<ResultCellSlab> getResultCellSlab() {
    return resultCellSlab;
  }

  public void setResultCellSlab(List<ResultCellSlab> resultCellSlab) {
    this.resultCellSlab = resultCellSlab;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ReadStateIndex instance itself
   */
  public ReadStateIndex putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReadStateIndex readStateIndex = (ReadStateIndex) o;
    return Objects.equals(this.doneAddingResultTiles, readStateIndex.doneAddingResultTiles) &&
        Objects.equals(this.fragTileIdx, readStateIndex.fragTileIdx) &&
        Objects.equals(this.resultCellSlab, readStateIndex.resultCellSlab)&&
        Objects.equals(this.additionalProperties, readStateIndex.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(doneAddingResultTiles, fragTileIdx, resultCellSlab, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReadStateIndex {\n");
    sb.append("    doneAddingResultTiles: ").append(toIndentedString(doneAddingResultTiles)).append("\n");
    sb.append("    fragTileIdx: ").append(toIndentedString(fragTileIdx)).append("\n");
    sb.append("    resultCellSlab: ").append(toIndentedString(resultCellSlab)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("doneAddingResultTiles");
    openapiFields.add("fragTileIdx");
    openapiFields.add("resultCellSlab");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ReadStateIndex
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ReadStateIndex.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ReadStateIndex is not found in the empty JSON string", ReadStateIndex.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("fragTileIdx") != null && !jsonObj.get("fragTileIdx").isJsonNull()) {
        JsonArray jsonArrayfragTileIdx = jsonObj.getAsJsonArray("fragTileIdx");
        if (jsonArrayfragTileIdx != null) {
          // ensure the json data is an array
          if (!jsonObj.get("fragTileIdx").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `fragTileIdx` to be an array in the JSON string but got `%s`", jsonObj.get("fragTileIdx").toString()));
          }

          // validate the optional field `fragTileIdx` (array)
          for (int i = 0; i < jsonArrayfragTileIdx.size(); i++) {
            FragmentIndex.validateJsonElement(jsonArrayfragTileIdx.get(i));
          };
        }
      }
      if (jsonObj.get("resultCellSlab") != null && !jsonObj.get("resultCellSlab").isJsonNull()) {
        JsonArray jsonArrayresultCellSlab = jsonObj.getAsJsonArray("resultCellSlab");
        if (jsonArrayresultCellSlab != null) {
          // ensure the json data is an array
          if (!jsonObj.get("resultCellSlab").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `resultCellSlab` to be an array in the JSON string but got `%s`", jsonObj.get("resultCellSlab").toString()));
          }

          // validate the optional field `resultCellSlab` (array)
          for (int i = 0; i < jsonArrayresultCellSlab.size(); i++) {
            ResultCellSlab.validateJsonElement(jsonArrayresultCellSlab.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ReadStateIndex.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ReadStateIndex' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ReadStateIndex> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ReadStateIndex.class));

       return (TypeAdapter<T>) new TypeAdapter<ReadStateIndex>() {
           @Override
           public void write(JsonWriter out, ReadStateIndex value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ReadStateIndex read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             ReadStateIndex instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ReadStateIndex given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ReadStateIndex
   * @throws IOException if the JSON string is invalid with respect to ReadStateIndex
   */
  public static ReadStateIndex fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ReadStateIndex.class);
  }

  /**
   * Convert an instance of ReadStateIndex to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

