/*
 * Specification file for tiledb-server v4 API
 * This spec is exposed to the public under /v4 route group
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@tiledb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tiledb.cloud.rest_api.v4.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AssetsMoveRequest
 */
public class AssetsMoveRequestTest {
    private final AssetsMoveRequest model = new AssetsMoveRequest();

    /**
     * Model tests for AssetsMoveRequest
     */
    @Test
    public void testAssetsMoveRequest() {
        // TODO: test AssetsMoveRequest
    }

    /**
     * Test the property 'assetsToAdd'
     */
    @Test
    public void assetsToAddTest() {
        // TODO: test assetsToAdd
    }

    /**
     * Test the property 'target'
     */
    @Test
    public void targetTest() {
        // TODO: test target
    }

}
