/*
 * Specification file for tiledb-server v4 API
 * This spec is exposed to the public under /v4 route group
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@tiledb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tiledb.cloud.rest_api.v4.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for QueryTableRequest
 */
public class QueryTableRequestTest {
    private final QueryTableRequest model = new QueryTableRequest();

    /**
     * Model tests for QueryTableRequest
     */
    @Test
    public void testQueryTableRequest() {
        // TODO: test QueryTableRequest
    }

    /**
     * Test the property 'predicateHints'
     */
    @Test
    public void predicateHintsTest() {
        // TODO: test predicateHints
    }

    /**
     * Test the property 'jsonPredicateHints'
     */
    @Test
    public void jsonPredicateHintsTest() {
        // TODO: test jsonPredicateHints
    }

    /**
     * Test the property 'limitHint'
     */
    @Test
    public void limitHintTest() {
        // TODO: test limitHint
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    public void timestampTest() {
        // TODO: test timestamp
    }

    /**
     * Test the property 'startingVersion'
     */
    @Test
    public void startingVersionTest() {
        // TODO: test startingVersion
    }

    /**
     * Test the property 'endingVersion'
     */
    @Test
    public void endingVersionTest() {
        // TODO: test endingVersion
    }

}
