/*
 * Specification file for tiledb-server v4 API
 * This spec is exposed to the public under /v4 route group
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@tiledb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tiledb.cloud.rest_api.v4.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.tiledb.cloud.rest_api.v4.model.SchemaFieldArrayElementType;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SchemaFieldArray
 */
public class SchemaFieldArrayTest {
    private final SchemaFieldArray model = new SchemaFieldArray();

    /**
     * Model tests for SchemaFieldArray
     */
    @Test
    public void testSchemaFieldArray() {
        // TODO: test SchemaFieldArray
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'elementType'
     */
    @Test
    public void elementTypeTest() {
        // TODO: test elementType
    }

    /**
     * Test the property 'containsNull'
     */
    @Test
    public void containsNullTest() {
        // TODO: test containsNull
    }

}
