/*
 * Specification file for tiledb-server v4 API
 * This spec is exposed to the public under /v4 route group
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@tiledb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tiledb.cloud.rest_api.v4.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import io.tiledb.cloud.rest_api.v4.model.Format;
import io.tiledb.cloud.rest_api.v4.model.Metadata;
import io.tiledb.cloud.rest_api.v4.model.Protocol;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TableMetadataResponse
 */
public class TableMetadataResponseTest {
    private final TableMetadataResponse model = new TableMetadataResponse();

    /**
     * Model tests for TableMetadataResponse
     */
    @Test
    public void testTableMetadataResponse() {
        // TODO: test TableMetadataResponse
    }

    /**
     * Test the property 'minReaderVersion'
     */
    @Test
    public void minReaderVersionTest() {
        // TODO: test minReaderVersion
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'format'
     */
    @Test
    public void formatTest() {
        // TODO: test format
    }

    /**
     * Test the property 'schema'
     */
    @Test
    public void schemaTest() {
        // TODO: test schema
    }

    /**
     * Test the property 'schemaString'
     */
    @Test
    public void schemaStringTest() {
        // TODO: test schemaString
    }

    /**
     * Test the property 'partitionColumns'
     */
    @Test
    public void partitionColumnsTest() {
        // TODO: test partitionColumns
    }

    /**
     * Test the property '_configuration'
     */
    @Test
    public void _configurationTest() {
        // TODO: test _configuration
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'size'
     */
    @Test
    public void sizeTest() {
        // TODO: test size
    }

    /**
     * Test the property 'numFiles'
     */
    @Test
    public void numFilesTest() {
        // TODO: test numFiles
    }

}
