/*
 * Specification file for tiledb-server v4 API
 * This spec is exposed to the public under /v4 route group
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@tiledb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tiledb.cloud.rest_api.v4.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.tiledb.cloud.rest_api.v4.JSON;

/**
 * Delta share table change file object for removals
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class DataChangeFileRemove {
  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  @javax.annotation.Nonnull
  private String url;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_PARTITION_VALUES = "partitionValues";
  @SerializedName(SERIALIZED_NAME_PARTITION_VALUES)
  @javax.annotation.Nonnull
  private Map<String, Object> partitionValues = new HashMap<>();

  public static final String SERIALIZED_NAME_SIZE = "size";
  @SerializedName(SERIALIZED_NAME_SIZE)
  @javax.annotation.Nonnull
  private Integer size;

  public static final String SERIALIZED_NAME_TIMESTAMP = "timestamp";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP)
  @javax.annotation.Nonnull
  private Integer timestamp;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  @javax.annotation.Nonnull
  private Integer version;

  public static final String SERIALIZED_NAME_EXPIRATION_TIMESTAMP = "expirationTimestamp";
  @SerializedName(SERIALIZED_NAME_EXPIRATION_TIMESTAMP)
  @javax.annotation.Nullable
  private Integer expirationTimestamp;

  public DataChangeFileRemove() {
  }

  public DataChangeFileRemove url(@javax.annotation.Nonnull String url) {
    this.url = url;
    return this;
  }

  /**
   * An https url that a client can use to read the file directly. The same file in different responses may have different urls.
   * @return url
   */
  @javax.annotation.Nonnull
  public String getUrl() {
    return url;
  }

  public void setUrl(@javax.annotation.Nonnull String url) {
    this.url = url;
  }


  public DataChangeFileRemove id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * A unique string for the file in a table. The same file is guaranteed to have the same id across multiple requests. A client may cache the file content and use this id as a key to decide whether to use the cached file content.
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public DataChangeFileRemove partitionValues(@javax.annotation.Nonnull Map<String, Object> partitionValues) {
    this.partitionValues = partitionValues;
    return this;
  }

  public DataChangeFileRemove putPartitionValuesItem(String key, Object partitionValuesItem) {
    if (this.partitionValues == null) {
      this.partitionValues = new HashMap<>();
    }
    this.partitionValues.put(key, partitionValuesItem);
    return this;
  }

  /**
   * A map from partition column to value for this file. See Partition Value Serialization for how to parse the partition values. When the table doesn&#39;t have partition columns, this will be an empty map.
   * @return partitionValues
   */
  @javax.annotation.Nonnull
  public Map<String, Object> getPartitionValues() {
    return partitionValues;
  }

  public void setPartitionValues(@javax.annotation.Nonnull Map<String, Object> partitionValues) {
    this.partitionValues = partitionValues;
  }


  public DataChangeFileRemove size(@javax.annotation.Nonnull Integer size) {
    this.size = size;
    return this;
  }

  /**
   * The size of this file in bytes.
   * @return size
   */
  @javax.annotation.Nonnull
  public Integer getSize() {
    return size;
  }

  public void setSize(@javax.annotation.Nonnull Integer size) {
    this.size = size;
  }


  public DataChangeFileRemove timestamp(@javax.annotation.Nonnull Integer timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * The timestamp of the file in milliseconds from epoch.
   * @return timestamp
   */
  @javax.annotation.Nonnull
  public Integer getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(@javax.annotation.Nonnull Integer timestamp) {
    this.timestamp = timestamp;
  }


  public DataChangeFileRemove version(@javax.annotation.Nonnull Integer version) {
    this.version = version;
    return this;
  }

  /**
   * The table version of this file.
   * @return version
   */
  @javax.annotation.Nonnull
  public Integer getVersion() {
    return version;
  }

  public void setVersion(@javax.annotation.Nonnull Integer version) {
    this.version = version;
  }


  public DataChangeFileRemove expirationTimestamp(@javax.annotation.Nullable Integer expirationTimestamp) {
    this.expirationTimestamp = expirationTimestamp;
    return this;
  }

  /**
   * The unix timestamp corresponding to the expiration of the url, in milliseconds, returned when the server supports the feature.
   * @return expirationTimestamp
   */
  @javax.annotation.Nullable
  public Integer getExpirationTimestamp() {
    return expirationTimestamp;
  }

  public void setExpirationTimestamp(@javax.annotation.Nullable Integer expirationTimestamp) {
    this.expirationTimestamp = expirationTimestamp;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataChangeFileRemove dataChangeFileRemove = (DataChangeFileRemove) o;
    return Objects.equals(this.url, dataChangeFileRemove.url) &&
        Objects.equals(this.id, dataChangeFileRemove.id) &&
        Objects.equals(this.partitionValues, dataChangeFileRemove.partitionValues) &&
        Objects.equals(this.size, dataChangeFileRemove.size) &&
        Objects.equals(this.timestamp, dataChangeFileRemove.timestamp) &&
        Objects.equals(this.version, dataChangeFileRemove.version) &&
        Objects.equals(this.expirationTimestamp, dataChangeFileRemove.expirationTimestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, id, partitionValues, size, timestamp, version, expirationTimestamp);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataChangeFileRemove {\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    partitionValues: ").append(toIndentedString(partitionValues)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    expirationTimestamp: ").append(toIndentedString(expirationTimestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("url", "id", "partitionValues", "size", "timestamp", "version", "expirationTimestamp"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("url", "id", "partitionValues", "size", "timestamp", "version"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DataChangeFileRemove
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DataChangeFileRemove.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DataChangeFileRemove is not found in the empty JSON string", DataChangeFileRemove.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DataChangeFileRemove.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DataChangeFileRemove` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DataChangeFileRemove.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("url").toString()));
      }
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DataChangeFileRemove.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DataChangeFileRemove' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DataChangeFileRemove> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DataChangeFileRemove.class));

       return (TypeAdapter<T>) new TypeAdapter<DataChangeFileRemove>() {
           @Override
           public void write(JsonWriter out, DataChangeFileRemove value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DataChangeFileRemove read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DataChangeFileRemove given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DataChangeFileRemove
   * @throws IOException if the JSON string is invalid with respect to DataChangeFileRemove
   */
  public static DataChangeFileRemove fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DataChangeFileRemove.class);
  }

  /**
   * Convert an instance of DataChangeFileRemove to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

