/*
 * Specification file for tiledb-server v4 API
 * This spec is exposed to the public under /v4 route group
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@tiledb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tiledb.cloud.rest_api.v4.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.tiledb.cloud.rest_api.v4.model.SchemaFieldArrayElementType;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.tiledb.cloud.rest_api.v4.JSON;

/**
 * An array stores a variable length collection of items of some type.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class SchemaFieldArray {
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nonnull
  private String type;

  public static final String SERIALIZED_NAME_ELEMENT_TYPE = "elementType";
  @SerializedName(SERIALIZED_NAME_ELEMENT_TYPE)
  @javax.annotation.Nonnull
  private SchemaFieldArrayElementType elementType;

  public static final String SERIALIZED_NAME_CONTAINS_NULL = "containsNull";
  @SerializedName(SERIALIZED_NAME_CONTAINS_NULL)
  @javax.annotation.Nonnull
  private Boolean containsNull;

  public SchemaFieldArray() {
  }

  public SchemaFieldArray type(@javax.annotation.Nonnull String type) {
    this.type = type;
    return this;
  }

  /**
   * Always the string array
   * @return type
   */
  @javax.annotation.Nonnull
  public String getType() {
    return type;
  }

  public void setType(@javax.annotation.Nonnull String type) {
    this.type = type;
  }


  public SchemaFieldArray elementType(@javax.annotation.Nonnull SchemaFieldArrayElementType elementType) {
    this.elementType = elementType;
    return this;
  }

  /**
   * Get elementType
   * @return elementType
   */
  @javax.annotation.Nonnull
  public SchemaFieldArrayElementType getElementType() {
    return elementType;
  }

  public void setElementType(@javax.annotation.Nonnull SchemaFieldArrayElementType elementType) {
    this.elementType = elementType;
  }


  public SchemaFieldArray containsNull(@javax.annotation.Nonnull Boolean containsNull) {
    this.containsNull = containsNull;
    return this;
  }

  /**
   * Boolean denoting whether this array can contain one or more null values
   * @return containsNull
   */
  @javax.annotation.Nonnull
  public Boolean getContainsNull() {
    return containsNull;
  }

  public void setContainsNull(@javax.annotation.Nonnull Boolean containsNull) {
    this.containsNull = containsNull;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SchemaFieldArray schemaFieldArray = (SchemaFieldArray) o;
    return Objects.equals(this.type, schemaFieldArray.type) &&
        Objects.equals(this.elementType, schemaFieldArray.elementType) &&
        Objects.equals(this.containsNull, schemaFieldArray.containsNull);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, elementType, containsNull);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SchemaFieldArray {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    elementType: ").append(toIndentedString(elementType)).append("\n");
    sb.append("    containsNull: ").append(toIndentedString(containsNull)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("type", "elementType", "containsNull"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("type", "elementType", "containsNull"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SchemaFieldArray
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SchemaFieldArray.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SchemaFieldArray is not found in the empty JSON string", SchemaFieldArray.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SchemaFieldArray.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SchemaFieldArray` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SchemaFieldArray.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      // validate the required field `elementType`
      SchemaFieldArrayElementType.validateJsonElement(jsonObj.get("elementType"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SchemaFieldArray.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SchemaFieldArray' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SchemaFieldArray> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SchemaFieldArray.class));

       return (TypeAdapter<T>) new TypeAdapter<SchemaFieldArray>() {
           @Override
           public void write(JsonWriter out, SchemaFieldArray value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SchemaFieldArray read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SchemaFieldArray given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SchemaFieldArray
   * @throws IOException if the JSON string is invalid with respect to SchemaFieldArray
   */
  public static SchemaFieldArray fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SchemaFieldArray.class);
  }

  /**
   * Convert an instance of SchemaFieldArray to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

