/*
 * Specification file for tiledb-server v4 API
 * This spec is exposed to the public under /v4 route group
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@tiledb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tiledb.cloud.rest_api.v4.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * A enum represents a field type
 */
@JsonAdapter(SchemaFieldDataType.Adapter.class)
public enum SchemaFieldDataType {
  
  STRING("string"),
  
  LONG("long"),
  
  INTEGER("integer"),
  
  SHORT("short"),
  
  BYTE("byte"),
  
  FLOAT("float"),
  
  DOUBLE("double"),
  
  BOOLEAN("boolean"),
  
  BINARY("binary"),
  
  DATE("date"),
  
  TIMESTAMP("timestamp"),
  
  DECIMAL("decimal"),
  
  ARRAY("array"),
  
  STRUCT("struct");

  private String value;

  SchemaFieldDataType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static SchemaFieldDataType fromValue(String value) {
    for (SchemaFieldDataType b : SchemaFieldDataType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<SchemaFieldDataType> {
    @Override
    public void write(final JsonWriter jsonWriter, final SchemaFieldDataType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public SchemaFieldDataType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return SchemaFieldDataType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    SchemaFieldDataType.fromValue(value);
  }
}

