/*
 * Specification file for tiledb-server v4 API
 * This spec is exposed to the public under /v4 route group
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@tiledb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tiledb.cloud.rest_api.v4.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.tiledb.cloud.rest_api.v4.JSON;

/**
 * A map stores an arbitrary length collection of key-value pairs with a single keyType and a single valueType.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class SchemaFieldMap {
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nonnull
  private String type;

  public static final String SERIALIZED_NAME_KEY_TYPE = "keyType";
  @SerializedName(SERIALIZED_NAME_KEY_TYPE)
  @javax.annotation.Nonnull
  private String keyType;

  public static final String SERIALIZED_NAME_VALUE_TYPE = "valueType";
  @SerializedName(SERIALIZED_NAME_VALUE_TYPE)
  @javax.annotation.Nonnull
  private String valueType;

  public static final String SERIALIZED_NAME_VALUE_CONTAINS_NULL = "valueContainsNull";
  @SerializedName(SERIALIZED_NAME_VALUE_CONTAINS_NULL)
  @javax.annotation.Nonnull
  private Boolean valueContainsNull;

  public SchemaFieldMap() {
  }

  public SchemaFieldMap type(@javax.annotation.Nonnull String type) {
    this.type = type;
    return this;
  }

  /**
   * Always the string map
   * @return type
   */
  @javax.annotation.Nonnull
  public String getType() {
    return type;
  }

  public void setType(@javax.annotation.Nonnull String type) {
    this.type = type;
  }


  public SchemaFieldMap keyType(@javax.annotation.Nonnull String keyType) {
    this.keyType = keyType;
    return this;
  }

  /**
   * The type of element used for the key of this map, represented as a string containing the name of a primitive type, a struct definition, an array definition or a map definition
   * @return keyType
   */
  @javax.annotation.Nonnull
  public String getKeyType() {
    return keyType;
  }

  public void setKeyType(@javax.annotation.Nonnull String keyType) {
    this.keyType = keyType;
  }


  public SchemaFieldMap valueType(@javax.annotation.Nonnull String valueType) {
    this.valueType = valueType;
    return this;
  }

  /**
   * The type of element used for the key of this map, represented as a string containing the name of a primitive type, a struct definition, an array definition or a map definition
   * @return valueType
   */
  @javax.annotation.Nonnull
  public String getValueType() {
    return valueType;
  }

  public void setValueType(@javax.annotation.Nonnull String valueType) {
    this.valueType = valueType;
  }


  public SchemaFieldMap valueContainsNull(@javax.annotation.Nonnull Boolean valueContainsNull) {
    this.valueContainsNull = valueContainsNull;
    return this;
  }

  /**
   * Indicates if map values have null values.
   * @return valueContainsNull
   */
  @javax.annotation.Nonnull
  public Boolean getValueContainsNull() {
    return valueContainsNull;
  }

  public void setValueContainsNull(@javax.annotation.Nonnull Boolean valueContainsNull) {
    this.valueContainsNull = valueContainsNull;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SchemaFieldMap schemaFieldMap = (SchemaFieldMap) o;
    return Objects.equals(this.type, schemaFieldMap.type) &&
        Objects.equals(this.keyType, schemaFieldMap.keyType) &&
        Objects.equals(this.valueType, schemaFieldMap.valueType) &&
        Objects.equals(this.valueContainsNull, schemaFieldMap.valueContainsNull);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, keyType, valueType, valueContainsNull);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SchemaFieldMap {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    keyType: ").append(toIndentedString(keyType)).append("\n");
    sb.append("    valueType: ").append(toIndentedString(valueType)).append("\n");
    sb.append("    valueContainsNull: ").append(toIndentedString(valueContainsNull)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("type", "keyType", "valueType", "valueContainsNull"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("type", "keyType", "valueType", "valueContainsNull"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SchemaFieldMap
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SchemaFieldMap.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SchemaFieldMap is not found in the empty JSON string", SchemaFieldMap.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SchemaFieldMap.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SchemaFieldMap` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SchemaFieldMap.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      if (!jsonObj.get("keyType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `keyType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("keyType").toString()));
      }
      if (!jsonObj.get("valueType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `valueType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("valueType").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SchemaFieldMap.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SchemaFieldMap' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SchemaFieldMap> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SchemaFieldMap.class));

       return (TypeAdapter<T>) new TypeAdapter<SchemaFieldMap>() {
           @Override
           public void write(JsonWriter out, SchemaFieldMap value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SchemaFieldMap read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SchemaFieldMap given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SchemaFieldMap
   * @throws IOException if the JSON string is invalid with respect to SchemaFieldMap
   */
  public static SchemaFieldMap fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SchemaFieldMap.class);
  }

  /**
   * Convert an instance of SchemaFieldMap to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

