/*
 * Specification file for tiledb-server v4 API
 * This spec is exposed to the public under /v4 route group
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@tiledb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tiledb.cloud.rest_api.v4.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.tiledb.cloud.rest_api.v4.JSON;

/**
 * Various version numbers for the server
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class Versions {
  public static final String SERIALIZED_NAME_GO_VERSION = "go_version";
  @SerializedName(SERIALIZED_NAME_GO_VERSION)
  @javax.annotation.Nonnull
  private String goVersion;

  public static final String SERIALIZED_NAME_TILEDB_VERSION = "tiledb_version";
  @SerializedName(SERIALIZED_NAME_TILEDB_VERSION)
  @javax.annotation.Nonnull
  private String tiledbVersion;

  public static final String SERIALIZED_NAME_UDF_IMAGES_VERSION = "udf_images_version";
  @SerializedName(SERIALIZED_NAME_UDF_IMAGES_VERSION)
  @javax.annotation.Nonnull
  private List<String> udfImagesVersion = new ArrayList<>();

  public static final String SERIALIZED_NAME_VCS_NAME = "vcs_name";
  @SerializedName(SERIALIZED_NAME_VCS_NAME)
  @javax.annotation.Nullable
  private String vcsName;

  public static final String SERIALIZED_NAME_VCS_REVISION = "vcs_revision";
  @SerializedName(SERIALIZED_NAME_VCS_REVISION)
  @javax.annotation.Nullable
  private String vcsRevision;

  public static final String SERIALIZED_NAME_VCS_TIME = "vcs_time";
  @SerializedName(SERIALIZED_NAME_VCS_TIME)
  @javax.annotation.Nullable
  private OffsetDateTime vcsTime;

  public static final String SERIALIZED_NAME_BUILD_ID = "build_id";
  @SerializedName(SERIALIZED_NAME_BUILD_ID)
  @javax.annotation.Nullable
  private String buildId;

  public Versions() {
  }

  public Versions goVersion(@javax.annotation.Nonnull String goVersion) {
    this.goVersion = goVersion;
    return this;
  }

  /**
   * The version of Go used to build the server
   * @return goVersion
   */
  @javax.annotation.Nonnull
  public String getGoVersion() {
    return goVersion;
  }

  public void setGoVersion(@javax.annotation.Nonnull String goVersion) {
    this.goVersion = goVersion;
  }


  public Versions tiledbVersion(@javax.annotation.Nonnull String tiledbVersion) {
    this.tiledbVersion = tiledbVersion;
    return this;
  }

  /**
   * The version of TileDB used by the server
   * @return tiledbVersion
   */
  @javax.annotation.Nonnull
  public String getTiledbVersion() {
    return tiledbVersion;
  }

  public void setTiledbVersion(@javax.annotation.Nonnull String tiledbVersion) {
    this.tiledbVersion = tiledbVersion;
  }


  public Versions udfImagesVersion(@javax.annotation.Nonnull List<String> udfImagesVersion) {
    this.udfImagesVersion = udfImagesVersion;
    return this;
  }

  public Versions addUdfImagesVersionItem(String udfImagesVersionItem) {
    if (this.udfImagesVersion == null) {
      this.udfImagesVersion = new ArrayList<>();
    }
    this.udfImagesVersion.add(udfImagesVersionItem);
    return this;
  }

  /**
   * The UDF images that the server supports
   * @return udfImagesVersion
   */
  @javax.annotation.Nonnull
  public List<String> getUdfImagesVersion() {
    return udfImagesVersion;
  }

  public void setUdfImagesVersion(@javax.annotation.Nonnull List<String> udfImagesVersion) {
    this.udfImagesVersion = udfImagesVersion;
  }


  public Versions vcsName(@javax.annotation.Nullable String vcsName) {
    this.vcsName = vcsName;
    return this;
  }

  /**
   * The name of the version control system (vcs) used to develop the server 
   * @return vcsName
   */
  @javax.annotation.Nullable
  public String getVcsName() {
    return vcsName;
  }

  public void setVcsName(@javax.annotation.Nullable String vcsName) {
    this.vcsName = vcsName;
  }


  public Versions vcsRevision(@javax.annotation.Nullable String vcsRevision) {
    this.vcsRevision = vcsRevision;
    return this;
  }

  /**
   * The vcs revision of the server
   * @return vcsRevision
   */
  @javax.annotation.Nullable
  public String getVcsRevision() {
    return vcsRevision;
  }

  public void setVcsRevision(@javax.annotation.Nullable String vcsRevision) {
    this.vcsRevision = vcsRevision;
  }


  public Versions vcsTime(@javax.annotation.Nullable OffsetDateTime vcsTime) {
    this.vcsTime = vcsTime;
    return this;
  }

  /**
   * The modification time associated with the vcs revision
   * @return vcsTime
   */
  @javax.annotation.Nullable
  public OffsetDateTime getVcsTime() {
    return vcsTime;
  }

  public void setVcsTime(@javax.annotation.Nullable OffsetDateTime vcsTime) {
    this.vcsTime = vcsTime;
  }


  public Versions buildId(@javax.annotation.Nullable String buildId) {
    this.buildId = buildId;
    return this;
  }

  /**
   * The build ID of the server. If set, this will be either the branch name or the git tag. 
   * @return buildId
   */
  @javax.annotation.Nullable
  public String getBuildId() {
    return buildId;
  }

  public void setBuildId(@javax.annotation.Nullable String buildId) {
    this.buildId = buildId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Versions versions = (Versions) o;
    return Objects.equals(this.goVersion, versions.goVersion) &&
        Objects.equals(this.tiledbVersion, versions.tiledbVersion) &&
        Objects.equals(this.udfImagesVersion, versions.udfImagesVersion) &&
        Objects.equals(this.vcsName, versions.vcsName) &&
        Objects.equals(this.vcsRevision, versions.vcsRevision) &&
        Objects.equals(this.vcsTime, versions.vcsTime) &&
        Objects.equals(this.buildId, versions.buildId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(goVersion, tiledbVersion, udfImagesVersion, vcsName, vcsRevision, vcsTime, buildId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Versions {\n");
    sb.append("    goVersion: ").append(toIndentedString(goVersion)).append("\n");
    sb.append("    tiledbVersion: ").append(toIndentedString(tiledbVersion)).append("\n");
    sb.append("    udfImagesVersion: ").append(toIndentedString(udfImagesVersion)).append("\n");
    sb.append("    vcsName: ").append(toIndentedString(vcsName)).append("\n");
    sb.append("    vcsRevision: ").append(toIndentedString(vcsRevision)).append("\n");
    sb.append("    vcsTime: ").append(toIndentedString(vcsTime)).append("\n");
    sb.append("    buildId: ").append(toIndentedString(buildId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("go_version", "tiledb_version", "udf_images_version", "vcs_name", "vcs_revision", "vcs_time", "build_id"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("go_version", "tiledb_version", "udf_images_version"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Versions
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Versions.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Versions is not found in the empty JSON string", Versions.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Versions.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Versions` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Versions.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("go_version").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `go_version` to be a primitive type in the JSON string but got `%s`", jsonObj.get("go_version").toString()));
      }
      if (!jsonObj.get("tiledb_version").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tiledb_version` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tiledb_version").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("udf_images_version") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("udf_images_version").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `udf_images_version` to be an array in the JSON string but got `%s`", jsonObj.get("udf_images_version").toString()));
      }
      if ((jsonObj.get("vcs_name") != null && !jsonObj.get("vcs_name").isJsonNull()) && !jsonObj.get("vcs_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `vcs_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("vcs_name").toString()));
      }
      if ((jsonObj.get("vcs_revision") != null && !jsonObj.get("vcs_revision").isJsonNull()) && !jsonObj.get("vcs_revision").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `vcs_revision` to be a primitive type in the JSON string but got `%s`", jsonObj.get("vcs_revision").toString()));
      }
      if ((jsonObj.get("build_id") != null && !jsonObj.get("build_id").isJsonNull()) && !jsonObj.get("build_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `build_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("build_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Versions.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Versions' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Versions> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Versions.class));

       return (TypeAdapter<T>) new TypeAdapter<Versions>() {
           @Override
           public void write(JsonWriter out, Versions value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Versions read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Versions given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Versions
   * @throws IOException if the JSON string is invalid with respect to Versions
   */
  public static Versions fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Versions.class);
  }

  /**
   * Convert an instance of Versions to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

